version: '3.9'

services:
#  api:
#    container_name: "BookShop_API"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - postgresql
#    ports:
#      - 8080:8081
#    env_file:
#      - ".env"
#    networks:
#      - backend
#    volumes:
#      - .:/app

  postgresql:
    image: postgres:15-alpine
    container_name: "MoneyMate_DB"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - ".env"
    networks:
      - backend

networks:
  backend:
    driver: bridge