my:
    secret-key: ${JWT_SECRET_KEY}

server:
    port: 8099

spring:
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        password: ${POSTGRES_PASSWORD}
        url: jdbc:postgresql://postgresql/${POSTGRES_DB}
        username: ${POSTGRES_USER}

    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true

    sql:
        init:
            platform: postgres
